### ISSUE TITLE
tabbing doesn't work for me

### ISSUE THREAD

**Issue by JoernT** [Collaborne/paper-password-input#10]
Using your wonderful control but it fails to advance the tabindex when hitting 'tab' while having focussed the control.

Have a form with a couple of <paper-input> elements and <paper-password-input> inbetween.

OS: macOS 10.12.5
browser: Chrome 59.0.3071.115
Polymer 2.0

**Comment by ronnyroeller** [comment]
New release with the fix is created.

You can see it in the demo "Password/confirm entry with match validation": https://www.webcomponents.org/element/Collaborne/paper-password-input/demo/demo/index.html

**Comment by JoernT** [comment]
Fantastic! That was quick. Thanks a bunch.
