### ISSUE TITLE
Input name

### ISSUE THREAD

**Issue by douglasrlee** [Collaborne/paper-password-input#2]
Can't set an input name with this.

**Comment by douglasrlee** [comment]
@ronnyroeller care if I make this fix?

**Comment by ankon** [comment]
What exactly are you trying to do?

(And, with that asked: is #3 supposed to fix this? If so, why did you close it?)

**Comment by douglasrlee** [comment]
Yeah, I didn't mean to make that PR here.

I need to be able to set the input name on the paper-input element that this is using.

**Comment by ankon** [comment]
I looked at this now, and your change in https://github.com/LegalShield/paper-password-input/pull/1 looks reasonable. So I'll be squashing that one into a single commit, and then commit it here.
