### ISSUE TITLE
min-length-validator is incorrect for empty string value

### ISSUE THREAD

**Issue by aaronanderson** [Collaborne/paper-password-input#5]
When the validate() method is called on a paper-password-input with an empty string the !value causes the function to return true. Since the validate() function is called on page load perhaps it should be left as-is but instead the required attribute should be added to paper-password-input and delegated to the paper-input.

**Comment by ronnyroeller** [comment]
Good point, @aaronanderson - that clearly lacked some documentation.

The validator ignores if the value is empty. This prevents showing a warning message before the user started to enter any content as requested by the Material Design specification: "Show error text only after user interaction with a field. If the user inputs incorrect data, helper text may transform into error text." (https://material.io/guidelines/patterns/errors.html#errors-user-input-errors).

I improved the code docu to clarify the current behavior.
